/**
 * Email sender — Resend transport for the daily digest + owner-only social snippet.
 *
 * Extracted from api/fetch-and-send.js so that api/digest-send.js can reuse the
 * exact same send paths. Behavior is unchanged from the previous inline version:
 *
 *   - sendDigest(): if TEST_EMAIL is set, sends to that address only (MVP /
 *     staging behavior). Otherwise creates a Resend broadcast against
 *     RESEND_AUDIENCE_ID and triggers send.
 *   - sendOwnerSnippetEmail(): drops a copy of today's social snippet into
 *     SNIPPET_EMAIL / OWNER_EMAIL so Pete can copy/paste to socials.
 *
 * Throws on send failures so callers can avoid setting "sent" idempotency
 * markers on a failed delivery.
 */

const RESEND_BASE = 'https://api.resend.com';
const FROM_ADDRESS = 'Buyside Brief <hello@buysidebrief.com>';

async function sendDigest(subject, html) {
  const RESEND_API_KEY = process.env.RESEND_API_KEY;
  if (!RESEND_API_KEY) {
    throw new Error('RESEND_API_KEY not set');
  }

  const AUDIENCE_ID = process.env.RESEND_AUDIENCE_ID;
  const TEST_EMAIL = process.env.TEST_EMAIL;

  if (TEST_EMAIL) {
    const res = await fetch(`${RESEND_BASE}/emails`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM_ADDRESS,
        to: [TEST_EMAIL],
        subject,
        html,
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Resend send failed: ${res.status} — ${err}`);
    }

    return await res.json();
  }

  if (AUDIENCE_ID) {
    // Resend renamed audiences to segments — segment_id is the current field.
    const createRes = await fetch(`${RESEND_BASE}/broadcasts`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        segment_id: AUDIENCE_ID,
        from: FROM_ADDRESS,
        subject,
        html,
      }),
    });

    if (!createRes.ok) {
      const err = await createRes.text();
      throw new Error(`Resend broadcast create failed: ${createRes.status} — ${err}`);
    }

    const broadcast = await createRes.json();

    const sendRes = await fetch(`${RESEND_BASE}/broadcasts/${broadcast.id}/send`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
    });

    if (!sendRes.ok) {
      const err = await sendRes.text();
      throw new Error(`Resend broadcast send failed: ${sendRes.status} — ${err}`);
    }

    return await sendRes.json();
  }

  throw new Error('No TEST_EMAIL or RESEND_AUDIENCE_ID configured');
}

async function sendOwnerSnippetEmail({ snippet, ticker }) {
  if (!snippet) return { sent: false, reason: 'no-snippet' };
  if (!process.env.RESEND_API_KEY) return { sent: false, reason: 'no-api-key' };

  const to = process.env.SNIPPET_EMAIL || process.env.OWNER_EMAIL;
  if (!to) return { sent: false, reason: 'no-recipient' };

  const html = `<div style="font-family:-apple-system,Helvetica,Arial,sans-serif;max-width:500px;padding:20px;">
    <p style="font-size:12px;color:#7a7a7a;margin:0 0 8px;">Copy and paste to Twitter/X or LinkedIn:</p>
    <div style="background:#faf8f4;border:1px solid #e0dbd3;border-radius:8px;padding:16px;font-size:15px;line-height:1.5;color:#1a1a1a;">
      ${snippet}
    </div>
    <p style="font-size:11px;color:#b0a99f;margin:12px 0 0;">Auto-generated by Buyside Brief AI</p>
  </div>`;

  const res = await fetch(`${RESEND_BASE}/emails`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: FROM_ADDRESS,
      to: [to],
      subject: `Today's social snippet — $${ticker || 'BB'}`,
      html,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Snippet email failed: ${res.status} — ${err}`);
  }

  return { sent: true, to, response: await res.json() };
}

module.exports = {
  sendDigest,
  sendOwnerSnippetEmail,
};
